// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"helloworld/internal/conf"
	"helloworld/internal/server"
	"helloworld/internal/service"
)

import (
	_ "helloworld/internal/biz"
	_ "helloworld/internal/data"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	demoService := service.NewDemoService()
	httpServer := server.NewHTTPServerDemo(confServer, demoService, logger)
	grpcServer := server.NewGRPCDemoServer(confServer, demoService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}
